language: julia

os: osx
julia: 1.0

before_install:
  - brew update
  - brew install ffmpeg

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("DeepWaterModels")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; cd(Pkg.dir("DeepWaterModels")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))';
