name = "WaterWaves1D"
uuid = "1a68f91a-d9eb-11e8-2e16-69ad0016fc96"
authors = ["Vincent Duchene <vincent.duchene@univ-rennes1.fr>", "Pierre Navaro <pierre.navaro@math.cnrs.fr>"]
version = "0.1.0"

[deps]
Elliptic = "b305315f-e792-5b7a-8f41-49f472929428"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Elliptic = "1"
FFTW = "^1"
HDF5 = "0.16, 0.17"
IterativeSolvers = "0.9"
LinearMaps = "3"
ProgressMeter = "1"
RecipesBase = "1"
julia = "^1.1"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Plots"]
